#!/usr/bin/env python3
"""Guarded OTA v2 -> plain USB -> OTA v2, through the existing USB bootloader.

Every bootloader step requires physical BOOT+RESET. Inspection is the default;
--apply authorizes one upload/reset step, never automatic image confirmation.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import secrets
import sys
import tempfile
import time

from lead_update import CampaignError, Journal, USBConnection, identity, json_value, select_port
from ota_artifact import inspect_usb_image
from usb_artifact import inspect_plain_usb
from prepare_ota_recovery import _object, require
from prepare_ota_transition import verify_config
from smp_transport import CommandError, SerialSMP
from bootloader_upload import upload_image, UploadError
from provision_ota import _verify_image, _provision_readiness


def _json(path):
    return json.loads(Path(path).read_bytes(), object_pairs_hook=_object)


def _save(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(json.dumps(value, indent=2, sort_keys=True, default=json_value) + "\n")
        stream.flush()
        import os
        os.fsync(stream.fileno())
    temporary.replace(path)


def capture(serial_number, output, *, port=None, connection_factory=USBConnection):
    require(isinstance(serial_number, str) and bool(serial_number), "explicit USB serial required")
    connection = connection_factory(serial_number, port)
    transport = connection.connect()
    try:
        info = transport.request("info")
        require(info.get("service") == "owntech-ota" and info.get("protocol") == 2,
                "capture requires the live OTA v2 application")
        identity(info.get("identity"))
        info = dict(info, usb_serial=serial_number, capture_id=secrets.token_hex(16))
        _save(output, info)
        return {"result": "CAPTURED", "info": str(output), "identity": identity(info["identity"])}
    finally:
        transport.close()


def _image(image_path, manifest_path, source, kind, *, build_id=None):
    data, manifest = Path(image_path).read_bytes(), _json(manifest_path)
    require(isinstance(manifest, dict) and isinstance(manifest.get("profile"), dict), "invalid image manifest")
    if kind == "usb":
        actual = inspect_plain_usb(data, manifest["profile"], manifest.get("version"), manifest.get("build_id"))
        proof = manifest.get("build_proof", {})
        require(manifest.get("execution_profile") == "usb" and isinstance(proof, dict)
                and proof.get("ota_enabled") is False and proof.get("recovery_enabled") is False
                and proof.get("auto_confirmation") is True,
                "plain USB requires the manifest generated by the verified USB build")
        for field in ("config_sha256", "elf_sha256"):
            require(isinstance(proof.get(field), str) and re.fullmatch(r"[0-9a-f]{64}", proof[field]),
                    "missing USB build provenance: " + field)
        require(manifest.get("build_id") == "usb-" + proof["elf_sha256"][:20], "USB build identity contradicts its ELF provenance")
    else:
        image_class = manifest.get("image_class", "receiver")
        if kind == "helper":
            require(manifest.get("version") == "0.0.1+0" and manifest.get("build_id") == build_id,
                    "helper artifact belongs to a different transition configuration")
        actual = inspect_usb_image(data, manifest["profile"], manifest.get("version"),
                                   manifest.get("build_id"), image_class, require_class=kind == "ota")
        if kind == "helper":
            # A transition helper has no OTA application class TLV.
            inspect_plain_usb(data, manifest["profile"])
    for field in ("protocol", "format", "activation_trailer", "artifact_size", "useful_size",
                  "artifact_sha256", "mcuboot_image_hash", "version", "build_id", "image_class",
                  "hardware_id", "layout_id", "bootloader_id"):
        require(manifest.get(field) == actual[field], "image bytes contradict manifest " + field)
    for field in ("slot_size", "useful_capacity", "header_size", "hardware_id", "layout_id", "bootloader_id"):
        require(actual["profile"].get(field) == source["profile"].get(field), "image hardware profile differs: " + field)
    require(manifest.get("signature", {}).get("key_sha256") == actual["signature"]["key_sha256"]
            == source["signature"]["key_sha256"], "image must use the existing signing key")
    return actual, data


def inputs(config_path, helper_path, helper_manifest, serial_number, target_identity):
    config = verify_config(config_path)
    require(identity(target_identity) == config["identity"], "board is outside this transition configuration")
    require(serial_number == config["usb_serial"] and bool(serial_number), "USB serial differs from captured board")
    helper, data = _image(helper_path, helper_manifest, config["source_manifest"], "helper",
                          build_id="transition-" + config["header_sha256"][:20])
    require(helper["mcuboot_image_hash"] != config["source_manifest"]["mcuboot_image_hash"],
            "helper and original application must be distinct")
    return config, helper, data


_COMPLETION = re.compile(rb"OTA_TRANSITION rc=(-?\d+) EUI=([0-9a-f]{16}) token=([0-9a-f]{64}) confirmed=([01]); outputs inhibited\r?\n")


def receipt_payload(config, helper, line):
    match = _COMPLETION.fullmatch(line)
    require(match is not None, "malformed transition completion record")
    require(match[2].decode() == config["identity"] and match[3].decode() == config["token"],
            "completion belongs to a different board or operation")
    require(int(match[1]) in (0, 1) and match[4] == b"1", "helper refused or has not confirmed and completed cleanup")
    return {"schema_version": 1, "identity": config["identity"], "usb_serial": config["usb_serial"],
            "token": config["token"], "header_sha256": config["header_sha256"],
            "helper_hash": helper["mcuboot_image_hash"], "line": line.decode("ascii")}


def verify_receipt(path, config, helper):
    receipt = _json(path)
    require(isinstance(receipt, dict) and isinstance(receipt.get("line"), str), "invalid cleanup receipt")
    expected = receipt_payload(config, helper, receipt["line"].encode("ascii"))
    require(receipt == expected, "cleanup receipt does not match this operation")
    return receipt


def _enumerator(enumerate_ports):
    if enumerate_ports is None:
        from serial.tools.list_ports import comports
        return comports
    return enumerate_ports


def collect_receipt(config, helper, output, *, port=None, timeout=30, enumerate_ports=None, console_factory=None):
    require(isinstance(timeout, (int, float)) and not isinstance(timeout, bool)
            and math.isfinite(timeout) and 0 < timeout <= 60, "receipt timeout must be within 0..60 seconds")
    enumerate_ports = _enumerator(enumerate_ports)
    device = select_port(enumerate_ports(), config["usb_serial"], port).device
    if console_factory is None:
        import serial
        console_factory = serial.Serial
    console = console_factory(device, baudrate=115200, timeout=0.2, write_timeout=0.2)
    try:
        # Never send SMP, console commands, or a 1200-baud reset to this utility.
        console.reset_input_buffer()
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            line = console.readline(257)
            require(len(line) <= 256, "transition console line exceeds bound")
            if not line.startswith(b"OTA_TRANSITION "):
                continue
            result = receipt_payload(config, helper, line)
            select_port(enumerate_ports(), config["usb_serial"], device)
            _save(output, result)
            return {"result": "CLEANUP_CONFIRMED", "receipt": str(output), "identity": config["identity"]}
        raise CampaignError("no completed transition observed; keep this helper and diagnose before any USB install")
    finally:
        console.close()


def _slots(state):
    # MCUboot boot_serial.c emits true flags only. bootable is required as
    # positive evidence that image-state reporting is enabled at all.
    require(isinstance(state, dict) and isinstance(state.get("images"), list) and state["images"],
            "empty or invalid bootloader image list")
    slots = {}
    for row in state["images"]:
        require(isinstance(row, dict) and type(row.get("slot")) is int and row["slot"] in (0, 1)
                and row["slot"] not in slots and type(row.get("image", 0)) is int and row.get("image", 0) == 0,
                "duplicate or unexpected image slot")
        require(isinstance(row.get("hash"), bytes) and len(row["hash"]) == 32 and isinstance(row.get("version"), str),
                "missing exact bootloader image identity")
        require(row.get("bootable") is True, "missing positive bootable/image-state capability")
        flags = {}
        for key in ("active", "confirmed", "pending", "permanent"):
            require(type(row.get(key, False)) is bool, "invalid image activation flag " + key)
            flags[key] = row.get(key, False)
        require(not flags["permanent"], "permanent pending swap is outside this transition")
        slots[row["slot"]] = dict(row, **flags)
    return slots


def _primary(state, expected_hash, expected_version=None, *, pending_candidate=False):
    slots = _slots(state)
    require(0 in slots and set(slots).issubset({0, 1}), "missing primary image")
    primary = slots[0]
    require(primary["hash"].hex() == expected_hash
            and (primary["active"] is True or (pending_candidate and 1 in slots and slots[1]["pending"]))
            and primary["confirmed"] is True and primary["pending"] is False,
            "primary is not the exact confirmed expected application")
    if expected_version is not None:
        require(primary["version"] + ("+0" if "+" not in primary["version"] else "") == expected_version,
                "primary version differs from the inspected artifact")
    if 1 in slots:
        require(slots[1]["active"] is False, "secondary cannot be active")
    return primary, slots.get(1)


def _candidate(state, primary, expected):
    active, secondary = _primary(state, primary["hash"].hex(), pending_candidate=True)
    # In MCUboot TEST state the still-confirmed original primary loses its
    # 'active' flag: the pending candidate is selected for the next boot.
    require({key: value for key, value in active.items() if key != "active"}
            == {key: value for key, value in primary.items() if key != "active"},
            "primary image state changed during upload")
    require(secondary is not None and secondary["hash"].hex() == expected["mcuboot_image_hash"]
            and secondary["pending"] is True and secondary["confirmed"] is False,
            "secondary is not the exact pending candidate")
    require(secondary["version"] + ("+0" if "+" not in secondary["version"] else "") == expected["version"],
            "candidate version differs from inspected artifact")


def _records(path):
    if not Path(path).is_file():
        return []
    data = Path(path).read_bytes()
    require(not data or data.endswith(b"\n"), "transaction log has an incomplete final record; preserve it for diagnosis")
    rows = [json.loads(line, object_pairs_hook=_object) for line in data.splitlines()]
    require(all(isinstance(row, dict) for row in rows), "transaction log records must be objects")
    return rows


def _has_event(path, token, event, image_hash):
    rows = _records(path)
    return any(row.get("token") == token and row.get("event") == event and row.get("image_hash") == image_hash for row in rows)


def bootloader_step(config, helper, stage, *, image=None, data=None, usb=None, receipt=None,
                    port=None, apply=False, resume=False, mcumgr=None, log_path=None, timeout=10,
                    enumerate_ports=None, transport_factory=None, uploader=None):
    require(stage in ("install-helper", "install-usb", "verify-usb", "return-ota"), "invalid transition step")
    require(isinstance(timeout, (int, float)) and not isinstance(timeout, bool)
            and math.isfinite(timeout) and 0 < timeout <= 60, "SMP timeout must be within 0..60 seconds")
    serial_number = config["usb_serial"]
    source = config["source_manifest"]
    if stage != "install-helper":
        require(receipt is not None, "a recorded cleanup completion is required")
        verify_receipt(receipt, config, helper)
    expected = source if stage == "install-helper" else helper if stage == "install-usb" else usb
    require(isinstance(expected, dict), "missing expected primary artifact")
    if stage != "verify-usb":
        require(isinstance(image, dict) and isinstance(data, bytes)
                and hashlib.sha256(data).hexdigest() == image["artifact_sha256"], "candidate snapshot mismatch")
        require(image["mcuboot_image_hash"] != expected["mcuboot_image_hash"], "candidate must differ from primary")
        if apply:
            require(mcumgr is not None and Path(mcumgr).is_file(), "apply requires the existing mcumgr executable")
    require(not resume or stage != "verify-usb", "verify-usb has no upload to resume")
    log_path = Path(log_path or (Path(config["inputs"]["board_info"]).parent / ("transition-" + config["token"][:16] + ".jsonl")))
    _records(log_path)  # Never append a new operation to an incomplete/corrupt log.
    candidate_hash = image["mcuboot_image_hash"] if image else expected["mcuboot_image_hash"]
    if resume:
        require(_has_event(log_path, config["token"], "TRANSITION_UPLOAD_REQUEST", candidate_hash)
                and _has_event(log_path, config["token"], "TRANSITION_SECONDARY_READY", candidate_hash),
                "resume requires the original secondary preparation and upload request in this operation's log")
    if stage == "return-ota":
        require(_has_event(log_path, config["token"], "USB_VERIFIED", expected["mcuboot_image_hash"]),
                "verify the confirmed plain USB application before returning to OTA")
    enumerate_ports = _enumerator(enumerate_ports)
    transport_factory, uploader = transport_factory or SerialSMP, uploader or upload_image
    device = select_port(enumerate_ports(), serial_number, port).device
    journal = Journal(log_path, 0)
    transport = None

    def emit(event, **values):
        journal.emit(event, config["identity"], token=config["token"], usb_serial=serial_number, stage=stage, **values)

    def check_port():
        select_port(enumerate_ports(), serial_number, device)

    def open_bootloader():
        nonlocal transport
        check_port()
        transport = transport_factory(device, timeout=timeout)
        try:
            transport.request("info")
        except CommandError as error:
            require(error.unsupported, "bootloader proof must be unsupported OTA group rc=8")
        else:
            raise CampaignError("live application replied; enter BOOT+RESET physically")

    def state(event):
        value = transport.image_state()
        emit(event, image_state=value)
        return value

    try:
        emit("TRANSITION_INPUT", apply=apply, resume=resume, image_hash=candidate_hash,
             header_sha256=config["header_sha256"], port=device)
        open_bootloader()
        initial = state("TRANSITION_INSPECT")
        primary, secondary = _primary(initial, expected["mcuboot_image_hash"], expected["version"], pending_candidate=resume)
        if stage == "verify-usb":
            # Ordinary USB development may have replaced the old helper backup.
            # The current USB build must still be exact, confirmed and proven
            # non-OTA; no pending swap is allowed in either slot.
            require(secondary is None or not secondary["pending"], "pending swap while verifying USB")
            emit("USB_VERIFIED", image_hash=expected["mcuboot_image_hash"])
            if apply:
                check_port()
                require(state("USB_BEFORE_RESET") == initial, "image state changed before reset")
                emit("TRANSITION_RESET_REQUEST")
                transport._request(2, 0, 5, "run verified USB application", {})
            return {"result": "USB_VERIFIED", "reset_requested": apply, "log": str(log_path)}
        if resume:
            _candidate(initial, primary, image)
        else:
            require(secondary is None or not secondary["pending"],
                    "pending secondary: stop; use --resume only for this tool's interrupted exact upload")
        if not apply:
            emit("TRANSITION_INSPECTED")
            return {"result": "RESUME_INSPECTED" if resume else "INSPECTED", "log": str(log_path)}
        check_port()
        require(state("TRANSITION_BEFORE_WRITE") == initial, "image state changed before mutation")
        if not resume:
            # Required even for an empty secondary: generic MCUboot serial
            # recovery can list the same images but defaults uploads to primary.
            # It does not implement this Zephyr image-management erase command.
            # Prove the intended service and slot before ever invoking upload.
            emit("TRANSITION_ERASE_REQUEST", secondary_hash=secondary["hash"].hex() if secondary else None)
            transport._request(2, 1, 5, "prepare inactive secondary slot", {"slot": 1})
            active, remaining = _primary(state("TRANSITION_AFTER_ERASE"), expected["mcuboot_image_hash"])
            require(active == primary and remaining is None, "erase did not preserve primary and empty secondary")
            emit("TRANSITION_SECONDARY_READY", image_hash=candidate_hash)
            transport.close()
            transport = None
            check_port()
            with tempfile.TemporaryDirectory(prefix="owntech-transition-") as temporary:
                snapshot = Path(temporary) / "firmware.mcuboot.bin"
                snapshot.write_bytes(data)
                base = [str(mcumgr), "--conntype", "serial", "--connstring",
                        "dev=%s,baud=115200,mtu=128" % device, "--timeout", "10", "--tries", "1"]
                emit("TRANSITION_UPLOAD_REQUEST", image_hash=candidate_hash, artifact_sha256=image["artifact_sha256"])
                uploader(base, snapshot)
            open_bootloader()
        _candidate(state("TRANSITION_AFTER_UPLOAD"), primary, image)
        check_port()
        emit("TRANSITION_RESET_REQUEST")
        transport._request(2, 0, 5, "boot verified transition candidate", {})
        emit("TRANSITION_RESET_ACCEPTED")
        return {"result": "RESET_REQUESTED", "stage": stage, "log": str(log_path)}
    except Exception as error:
        emit("TRANSITION_STOPPED", error=str(error))
        raise
    finally:
        if transport:
            transport.close()
        journal.close()


def verify_ota(config, manifest, *, port=None, connection_factory=USBConnection):
    connection = connection_factory(config["usb_serial"], port)
    transport = connection.connect()
    try:
        info = transport.request("info")
        require(identity(info.get("identity")) == config["identity"], "OTA EUI differs from selected board")
        _verify_image(info, manifest)
        require(info.get("maintenance", False if manifest["image_class"] == "lead" else None) is False
                and _provision_readiness(info) in ("READY", "WAITING_FOR_PEER"),
                "OTA application has not reached a confirmed clean ready state")
        return {"result": "OTA_VERIFIED", "identity": config["identity"], "info": info}
    finally:
        transport.close()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("step", choices=("capture", "install-helper", "receipt", "install-usb", "verify-usb", "return-ota", "verify-ota"))
    parser.add_argument("--serial", required=True)
    parser.add_argument("--port")
    parser.add_argument("--identity")
    parser.add_argument("--info", type=Path, help="capture output")
    parser.add_argument("--config", type=Path)
    parser.add_argument("--helper", type=Path)
    parser.add_argument("--helper-manifest", type=Path)
    parser.add_argument("--usb-image", type=Path)
    parser.add_argument("--usb-manifest", type=Path)
    parser.add_argument("--ota-image", type=Path)
    parser.add_argument("--ota-manifest", type=Path)
    parser.add_argument("--receipt", type=Path)
    parser.add_argument("--log", type=Path)
    parser.add_argument("--mcumgr", type=Path)
    parser.add_argument("--timeout", type=float, default=10)
    parser.add_argument("--resume", action="store_true", help="only reset this operation's already uploaded exact pending candidate")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--inspect", action="store_true", help="default for bootloader upload steps")
    args = parser.parse_args(argv)
    try:
        if args.step == "capture":
            require(args.info is not None, "capture requires --info output")
            result = capture(args.serial, args.info, port=args.port)
        else:
            require(all((args.config, args.helper, args.helper_manifest, args.identity)),
                    "step requires --config, --helper, --helper-manifest and --identity")
            config, helper, helper_data = inputs(args.config, args.helper, args.helper_manifest, args.serial, args.identity)
            if args.step == "receipt":
                require(args.receipt is not None, "receipt requires --receipt output")
                result = collect_receipt(config, helper, args.receipt, port=args.port, timeout=args.timeout)
            else:
                usb = ota = None
                if args.step in ("install-usb", "verify-usb", "return-ota"):
                    require(args.usb_image and args.usb_manifest, "step requires --usb-image and --usb-manifest")
                    usb, usb_data = _image(args.usb_image, args.usb_manifest, config["source_manifest"], "usb")
                if args.step in ("return-ota", "verify-ota"):
                    require(args.ota_image and args.ota_manifest, "step requires --ota-image and --ota-manifest")
                    ota, ota_data = _image(args.ota_image, args.ota_manifest, config["source_manifest"], "ota")
                if args.step == "verify-ota":
                    result = verify_ota(config, ota, port=args.port)
                else:
                    image, data = ((helper, helper_data) if args.step == "install-helper" else
                                   (usb, usb_data) if args.step == "install-usb" else
                                   (ota, ota_data) if args.step == "return-ota" else (None, None))
                    result = bootloader_step(config, helper, args.step, image=image, data=data, usb=usb,
                                             receipt=args.receipt, port=args.port, apply=args.apply, resume=args.resume,
                                             mcumgr=args.mcumgr, log_path=args.log, timeout=args.timeout)
        print(json.dumps(result, sort_keys=True, default=json_value))
        return 0
    except (OSError, ValueError, CampaignError, UploadError) as error:
        print("Transition stopped: %s" % error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
